# FEP → SCZ cross-dataset evaluation — svm

seed: 42

dataset_config: "configs/dataset/scz.yaml"

# ML Model details
ml_model: "svm"


source_dataset_id: "ds003944"

# Evaluation
use_subject_vote: true
class_names: ["HC", "SZ"]

# Feature extraction
ml_features:
  domains: ["dft", "time", "dwt", "cwt"]
  band_limits:
    - [0.5,  4.0]    # delta
    - [4.0,  8.0]    # theta
    - [8.0,  13.0]   # alpha
    - [13.0, 30.0]   # beta
    - [30.0, 45.0]   # gamma
  wavelet: "db4"
  cwt_wavelet: "morl"
  n_jobs: 8

# DataLoader override for ML
normalize: false

# WandB
use_wandb: true
wandb_project: "eeg-cross-eval"
wandb_entity: null                  # your W&B entity/team
wandb_run_name: null
wandb_mode: "offline"
wandb_dir: "outputs/wandb/scz/"
wandb_data_dir: "outputs/wandb/scz/_wandb_data"
wandb_upload_terminal_log_artifact: true

# Terminal/File Logs
terminal_log_dir: "outputs/logs/scz/eval"

# Confusion matrix
figures_dir: "outputs/figures/scz/eval"

# Checkpoints
checkpoint_path: "outputs/checkpoints/train_ml/svm/ds003944/fep/seed42/full/svm_full_pipeline.pkl"          # model trained on all FEP participants
rolling_checkpoint_dir: "outputs/checkpoints/train_ml/svm/ds003944/fep/seed42"   # five-fold CV models (run1 … run5)
